/* CONTEXT: This query was originally developed in SQLX within Google Cloud Dataform 
   and has been translated to standard BigQuery SQL.
   PURPOSE: LTV Prediction - Segments users by first basket size to calculate strict 12-month Lifetime Value.
*/

WITH first_orders AS (
  -- 1. Identify the very first completed/shipped order for each user within the 2-year snapshot.
  SELECT
    user_id,
    order_id,
    created_at AS first_order_date
  FROM
    `apex-activewear.silver_layer.stg_orders`
  WHERE
    status IN ('Complete', 'Shipped')
    AND created_at >= '2023-01-09' 
    AND created_at <= '2025-01-09'
  -- QUALIFY filters the window function results immediately, grabbing only row 1 (the first order).
  QUALIFY ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at ASC) = 1
),

first_order_value AS (
  -- 2. Calculate the total revenue of that specific first order (the initial basket size).
  SELECT
    fo.user_id,
    fo.first_order_date,
    SUM(oi.sale_price) AS first_basket_size
  FROM
    first_orders AS fo
  JOIN
    `apex-activewear.silver_layer.stg_order_items` AS oi 
    ON fo.order_id = oi.order_id
  GROUP BY
    1, 2
),

ltv_12m_data AS (
  -- 3. Calculate all subsequent revenue generated by the user within 1 year of their first order.
  SELECT
    fo.user_id,
    SUM(oi.sale_price) AS ltv_12_months
  FROM
    `apex-activewear.silver_layer.stg_order_items` AS oi
  JOIN
    first_orders AS fo 
    ON oi.user_id = fo.user_id
  WHERE
    oi.status = 'Complete' 
    AND DATE(oi.created_at) >= DATE(fo.first_order_date)
    AND DATE(oi.created_at) <= DATE_ADD(DATE(fo.first_order_date), INTERVAL 1 YEAR)
  GROUP BY
    1
)

-- 4. Final Output: Merge first basket size with 12-month LTV and apply the High/Low segmentation logic.
SELECT
  fov.user_id,
  fov.first_basket_size,
  -- If a user made no further purchases, their 12-month LTV is simply their first basket size.
  COALESCE(lt.ltv_12_months, fov.first_basket_size) AS ltv_12_months,
  CASE 
    WHEN fov.first_basket_size > 90 THEN 'High Value (> $90)' 
    ELSE 'Low Value (<= $90)' 
  END AS customer_segment
FROM
  first_order_value AS fov
LEFT JOIN
  ltv_12m_data AS lt 
  ON fov.user_id = lt.user_id;

/* CONTEXT: This query was originally developed in SQLX within Google Cloud Dataform 
   and has been translated to standard BigQuery SQL.
   PURPOSE: Segmented Retention - Compares the 12-month retention curves of High Value vs. Low Value cohorts.
*/

WITH First_Orders AS (
  -- 1. Identify the first order for every user.
  SELECT
    user_id,
    order_id,
    created_at AS first_order_date
  FROM
    `apex-activewear.silver_layer.stg_orders`
  WHERE
    status IN ('Complete', 'Shipped')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at ASC) = 1 
),

User_Segments AS (
  -- 2. Tag each user as High Value or Low Value based on their first order's item total.
  SELECT
    fo.user_id,
    fo.first_order_date,
    CASE
      WHEN SUM(oi.sale_price) > 90 THEN 'High Value (>$90)'
      ELSE 'Low Value (<=$90)'
    END AS segment
  FROM
    First_Orders AS fo
  JOIN
    `apex-activewear.silver_layer.stg_order_items` AS oi
    ON fo.order_id = oi.order_id
  GROUP BY
    1, 2 
),

Segment_Sizes AS (
  -- 3. Count the total number of users that fall into each segment to use as the denominator.
  SELECT
    segment,
    COUNT(user_id) AS initial_users
  FROM
    User_Segments
  GROUP BY
    1 
),

Retention_Activity AS (
  -- 4. Track how many distinct users from each segment made purchases in the months following their first order.
  SELECT
    us.segment,
    DATE_DIFF(DATE(o.created_at), DATE(us.first_order_date), MONTH) AS month_number,
    COUNT(DISTINCT o.user_id) AS active_users
  FROM
    User_Segments AS us
  JOIN
    `apex-activewear.silver_layer.stg_orders` AS o
    ON us.user_id = o.user_id
  WHERE
    o.status IN ('Complete', 'Shipped')
    AND o.created_at >= us.first_order_date
  GROUP BY
    1, 2 
)

-- 5. Final Output: Calculate the percentage of retained users per segment, per month.
SELECT
  ra.segment,
  ra.month_number,
  ss.initial_users,
  ra.active_users,
  ROUND((ra.active_users / ss.initial_users) * 100, 2) AS retention_rate_pct
FROM
  Retention_Activity AS ra
JOIN
  Segment_Sizes AS ss
  ON ra.segment = ss.segment
WHERE
  ra.month_number BETWEEN 0 AND 12
ORDER BY 
  ra.segment DESC, 
  ra.month_number ASC;
